######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 17 19:27:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakegame.h
SOURCES += main.cpp snakegame.cpp
