######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 10:18:34 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h
SOURCES += adder.cpp main.cpp
