######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 26 11:42:06 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += widget
# Input
SOURCES += first.cpp
