######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 11:34:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mytime.h
SOURCES += main.cpp mytime.cpp
