######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 08:59:32 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += changevalue.cpp
