######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 09:31:28 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += adder1.cpp
