######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 26 16:16:27 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += parentwin.cpp
