######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 17:10:35 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qq.h qqlogin.h
FORMS += qq.ui
SOURCES += main.cpp qqlogin.cpp
