######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 27 16:47:05 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h
FORMS += jfq.ui
SOURCES += adder.cpp main.cpp
