######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 26 14:52:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += closelab.cpp
